### ISSUE TITLE
Allow ChildContainers to be created

### ISSUE THREAD

**Issue by asg0451** [serenity-rs/songbird#107]
Currently childcontainers cannot be created to allow for custom child-process-based audio sources, since they contain a private field: https://github.com/serenity-rs/songbird/blob/df64ad92e5dc150790be2216c4e79b6fefa4964a/src/input/child.rs#L21

**Comment by asg0451** [comment]
seemed simple enough: #108

**Comment by FelixMcFelix** [comment]
Closed by #108.
