### ISSUE TITLE
Restartable::ytdl and Restartable::ytdl_search pauses the current track playing

### ISSUE THREAD

**Issue by peppizza** [serenity-rs/songbird#12]
I am unsure if this is intentional, and if it is, is there a way to keep the track playing while using the call, or is it a bug

**Comment by FelixMcFelix** [comment]
Hi, can you please clarify:
* What series of commands/track-plays/loop events occur to trigger this?
* Which track pauses?
* Is the track state `Paused`? `Stopped`?
* Does it stutter briefly? Or does it stop completely?

**Comment by peppizza** [comment]
```rust
use super::consts::SONGBIRD_EXPECT;

use serenity::{
    framework::standard::{macros::command, Args, CommandResult},
    model::prelude::*,
    prelude::*,
};

use songbird::input::Restartable;

#[command]
#[only_in(guilds)]
async fn play(ctx: &Context, msg: &Message, mut args: Args) -> CommandResult {
    let url = args.single_quoted::<String>()?;
    let guild_id = msg.guild_id.unwrap();

    let source = match Restartable::ytdl(url) {
        Ok(source) => source,
        Err(e) => {
            panic!(e);
        }
    };

    msg.reply(ctx, "done with ytdl call").await?;

    let manager = songbird::get(ctx).await.expect(SONGBIRD_EXPECT).clone();

    let handler_lock = manager.get(guild_id).unwrap();

    let mut handler = handler_lock.lock().await;

    handler.enqueue_source(source.into());

    Ok(())
}
```

There's an incredibly stripped version of my play command that demonstrates the issue.  The track stops completely until the ytdl call finishes as indicated by the reply.  When the track comes back on, it is sped up slightly, which I assume can be attributed to the driver catching up.  To reproduce the issue you simply have to call play and when the track is playing call it again to queue another track, and the currently playing track will stop until the ytdl call is finished, in which case it will resume slightly sped up

**Comment by peppizza** [comment]
If you want you can join a testing server I have on discord for a demonstration of the issue

**Comment by FelixMcFelix** [comment]
I think this might be due to `executor::block_on` being internally called [here](https://github.com/serenity-rs/songbird/blob/current/src/input/restartable.rs#L77-L79): the initial design of restartable sources needed to be usable from synchronous code. If you're using the simple tokio runtime (single-threaded) then this will prevent packet transmission (which is also an async task on the same runtime).

There is a separate issue where a new source with a long start time might cause pauses by blocking the driver, but that will be harder to solve.

**Comment by peppizza** [comment]
Doesn't the tokio::main macro use the multi-threaded driver by default? (which is what I'm using), or does code need to change internally to utilize multi-threading

**Comment by FelixMcFelix** [comment]
Tokio's `"rt-threaded"` or `"full"` features get you the multi-threaded scheduler. For now, this is the only mechanism I can think of which might hold up the driver before the track is handed over.

**Comment by peppizza** [comment]
Enabling the multi-threaded driver fixes the issue, I think it should be mentioned in the docs that it's a blocking call, unless you want to switch it to a non-blocking call, along with #10
