### ISSUE TITLE
Compatibility with Serenity 0.11

### ISSUE THREAD

**Issue by cryptoAlgorithm** [serenity-rs/songbird#126]
Hi, I've been trying to make the most basic voice example work in serenity, however ive ran into a block when implementing it into my own project as it doesn't seem to support serenity 0.10.

The example uses `.register_songbird()` on the ClientBuilder instance to register songbird, however that does not seem to be present when using Serenity 0.11. It however works when downgraded to serenity 0.10 (with the same code), but unfortunately that does not support Gateway Intents which I rely on. 

Can the examples be updated with working code for the latest version of serenity, or is there any workaround that allows me to use songbird with Serenity 0.11?

Thanks!

**Comment by cryptoAlgorithm** [comment]
Turns out, the latest stable version of songbird only works with up to serenity v0.10, even though the latest stable version of serenity is 0.11. You have to use the `next` branch of songbird for serenity >= v0.11 compatibility

**Comment by FelixMcFelix** [comment]
Solved by v0.3.
