### ISSUE TITLE
Add support for `tokio-tungstenite`.

### ISSUE THREAD

**Issue by FelixMcFelix** [serenity-rs/songbird#129]
This will prevent twilight users from compiling two separate Websocket libraries. Ideally, this should be implemented as an additive feature: having features for both backends selected should add a parameter to `Config` to choose this at runtime (with an arbitrary default).

**Comment by nickelc** [comment]
What do you think about switching serenity and songbird to `tokio-tungstenite`?

**Comment by FelixMcFelix** [comment]
That should be fine, and means we don't need to worry about all the conditional config that would come up if we supported two backends. While I'm not sure what the exact library differences are, this seems reasonable versus supporting many backends if serenity makes the switch.

**Comment by nickelc** [comment]
It's mostly just `s/async_tungstenite/tokio_tungstenite/`.

**Comment by nickelc** [comment]
Check for the required changes in serenity 
- https://github.com/serenity-rs/serenity/pull/2036
