### ISSUE TITLE
Discord sending opcode 14 for client_disconnect

### ISSUE THREAD

**Issue by peppizza** [serenity-rs/songbird#14]
Unsure if this is an error with this library or serenity, however the error originated from songbird,  It seems discord, out of nowhere, is sending opcode 14 for client_disconnect, as well as the usual 13, as indicated by 
```songbird::driver::tasks::ws: Unexpected JSON Error("invalid value: integer `14`, expected opcode in [0--9] + [12--13]", line: 1, column: 8)```
This warning occurs when i disconnect from a voice channel and leave the bot alone in it

**Comment by FelixMcFelix** [comment]
Opcode 14 isn't documented, so from the bot's perspective is an illegal (but non-fatal) payload. Best guess is that it lists the current audio/video codec which all connected users are capable of.

EDIT: As I remember, one is sent with *every* Client (Dis)connect, and updates according to the remaining number of users and bots (i.e., a channel left with only bots will reduce to only an audio codec). This isn't something we can or should react to unless Discord describe the semantics.
