### ISSUE TITLE
(next) `tracks::create_player` missing

### ISSUE THREAD

**Issue by vilgotf** [serenity-rs/songbird#140]
Although [documented](https://serenity-rs.github.io/songbird/next/songbird/tracks/fn.create_player.html), this function does not exists in the source code, and is impossible to import.

**Comment by FelixMcFelix** [comment]
It's not that it's missing, it's removed -- the docs are wrong, and you're being served an old cached version of the function's docs! It looks as though this somehow survived the swap to the smart intra-doc links, hence why it hasn't come up. I'll modify shortly.

**Comment by FelixMcFelix** [comment]
Okay, should be remedied -- thanks for being so observant!
