### ISSUE TITLE
Trouble building on Windows

### ISSUE THREAD

**Issue by Nagispace** [serenity-rs/songbird#159]
**Songbird version:** 0.3.0

**Rust version (`rustc -V`):** rustc 1.64.0 (a55dd71d5 2022-09-19)

**Serenity version:** 0.11

**Output of `ffmpeg -version`, `yt-dlp --version` (if relevant):** n/a

**Output of `rustup show`**: 
```
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\[my_username]\.rustup

stable-x86_64-pc-windows-msvc (default)
rustc 1.64.0 (a55dd71d5 2022-09-19)
```

**Description:**

Trying to run `cargo run`on windows will fail at building audiopus_sys v0.2.2 (see error log)
[error_log.txt](https://github.com/serenity-rs/songbird/files/10527304/error_log.txt)

**Steps to reproduce:**
n/a

**Comment by FelixMcFelix** [comment]
Hi, did you read the logs?

```
is `cmake` not installed?
```

I suggest you install CMake and make sure that it's visible on your path (i.e., 'Edit the system environment variables' on Win11).

**Comment by Nagispace** [comment]
> Hi, did you read the logs?
> 
> ```
> is `cmake` not installed?
> ```
> 
> I suggest you install CMake and make sure that it's visible on your path (i.e., 'Edit the system environment variables' on Win11).

Cmake was indeed installed but not in the PATH
