### ISSUE TITLE
There should be a way to get all `Arc<Mutex<Call>>`s 

### ISSUE THREAD

**Issue by fee1-dead** [serenity-rs/songbird#165]
**Songbird version:** next

**Description:**

I'm currently implementing a procedure for saving call information (including tracks from the builtin queue) to disk, but it looks like the `Songbird` type does not provide access to iter over all calls? Should this feature be added or am I approaching it in a wrong way?

**Comment by FelixMcFelix** [comment]
This is an API oversight, but I think it might be a little bit rougher to implement than it initially appears. Internally, we use a `DashMap` to store `Call`s -- you'd need to look into the best way to expose this without leaking internal implementation details.

**Comment by fee1-dead** [comment]
Fixed by #166. Closing.
