### ISSUE TITLE
How to play/load audio source from base64

### ISSUE THREAD

**Issue by beig** [serenity-rs/songbird#196]
Hello,

I am pretty new to rust but creating a discord bot seems like a nice project.

I am storing my mp3 as base64 string in jammdb.
Is there a way to load the sound directly from memory?
The only way I found is writing the base64 to a file and then load it

Thanks

**Comment by FelixMcFelix** [comment]
If you're on `next`, then you should be able to play any supported file format from memory ([every owned byte slice](https://serenity-rs.github.io/songbird/next/songbird/input/enum.Input.html#impl-From%3CT%3E-for-Input) e.g., `&'static [u8]`, `Bytes`, or `Vec<u8>`). Obviously you'd need to parse the Base64 string back into actual bytes.

If you're on `current`, then you're correct, you either need to write it out to a local file, transform and pipe it to ffmpeg, or decode it locally into raw `f32`s/`i16`s.
