### ISSUE TITLE
add custom arg for ffmpeg

### ISSUE THREAD

**Issue by thedtvn** [serenity-rs/songbird#201]
add custom arg for ffmpeg for playing steam data that not auto stop audio or make like -reconnect

**Comment by Skarlett** [comment]
Assuming you're referring to the `current` branch. Perhaps this is the [piece of code you're looking for?](https://github.com/serenity-rs/songbird/blob/current/src/input/ytdl_src.rs#L100-L108)

You can prepend arguments to [_ytdl](https://github.com/serenity-rs/songbird/blob/current/src/input/ytdl_src.rs#L39C1-L39C74) via `pre_args`

**Comment by thedtvn** [comment]
@Skarlett i like to play audio raw and pass args to ffmpeg to that go play some live audio and make it none stop before audio end

**Comment by thedtvn** [comment]
like 
```rs
// Extra command line arguments to pass to ffmpeg before the -i flag.
let before_options = ["-reconnect", "1", "-reconnect_streamed", "1", "-reconnect_delay_max", "10"];
//  Extra command line arguments to pass to ffmpeg after the -i flag.
let after_options = ["-vn"];
let data = Restartable::ffmpeg("<audio url>", before_options, after_options , false).await.unwrap();
````

**Comment by thedtvn** [comment]
i see  `songbird::input::ffmpeg_optioned` that  fix this sory

**Comment by thedtvn** [comment]
i use `songbird::input::ffmpeg_optioned` 
```rs
ffmpeg_optioned("<audio url>", &[], &[
     "-f",
     "s16le",
     "-ac",
     stereo_val,
     "-ar",
     "48000",
     "-acodec",
     "pcm_s16le",
     "-",
 ])
```
 and bot show is Audio Detected but is has no audio
