### ISSUE TITLE
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Ws(Json(Error("invalid value: integer `18`, expected opcode in [0--9] + [12--13]", line: 1, column: 8)))', src\main.rs:159:218

### ISSUE THREAD

**Issue by thedtvn** [serenity-rs/songbird#202]
**Songbird version:** songbird = { version = "0.3.2", features = ["driver"] }

**Rust version (`rustc -V`):** rustc 1.72.0 (5680fa18f 2023-08-23)

**Serenity/Twilight version:** custom client

**Description:**
```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Ws(Json(Error("invalid value: integer `18`, expected opcode in [0--9] + [12--13]", line: 1, column: 8)))', src\main.rs:159:218
```
got this err on connect

**Steps to reproduce:**
```
let mut dr = Driver::new(Config::default());
 dr.connect(ConnectionInfo {channel_id: Some(ChannelId(channel_id)), endpoint: endpoint.to_string(), guild_id: GuildId(guild_id), session_id: session_id.clone(), token, user_id: UserId(user_id)}).await.unwrap();
 ```

**Comment by FelixMcFelix** [comment]
Could you please provide a more detailed stacktrace (e.g., `RUST_BACKTRACE=full`)? Currently this is inadequate for me to see where in songbird the panic has occurred.

**Comment by thedtvn** [comment]
> Could you please provide a more detailed stacktrace (e.g., `RUST_BACKTRACE=full`)? Currently this is inadequate for me to see where in songbird the panic has occurred.

@FelixMcFelix is err on call connect

**Comment by thedtvn** [comment]
close fix when down ver of shuttle

**Comment by Erk-** [comment]
I believe this is a duplicate of https://github.com/serenity-rs/songbird/issues/172
