### ISSUE TITLE
Track metadata in TrackHandle

### ISSUE THREAD

**Issue by saanuregh** [serenity-rs/songbird#24]
Being able to access track metadata from TrackHandle struct would be very useful, like in use cases such as listing queue or transitioning from one song to another.

**Comment by FelixMcFelix** [comment]
Thanks for the input! I think this aligns very closely with what the author of #17 was trying to achieve.

I believe currently that the best way to go about this might be to store an `Arc<Metadata>` in `Input`s and `TrackHandle`s. Where this gets hazier is in the event that a user wants to modify the metadata themselves; I know of one or two users who query and fill this in from another external API.

The drawback of this is that it limits any `Metadata` edits to occur between the creation of an `Input` and the creation of a `Track(Handle)`—this is fine if we're clear about it in docs. I think it's probably far better than having any locking or having the metadata be queried and copied in the same way as `TrackState` needs to be.

**Comment by peppizza** [comment]
I think it would also be useful to (optionally) store the author of the message that triggered the entry of the track, as It would be useful to store who "created" a track as right now in my bot, I have to manage a hashmap with a custom metadata and author struct using the uuid (https://github.com/peppizza/music-bot/blob/master/src/state.rs#L151)

**Comment by FelixMcFelix** [comment]
@peppizza The function and design of metadata is independent of the simple queue, but I'll have a think about how to plug in additional read-only data.

**Comment by peppizza** [comment]
I originally thought of a typemap but that might not be very efficient to have one for every trackhandle and constantly be creating them
