### ISSUE TITLE
PlayMode

### ISSUE THREAD

**Issue by penguingl** [serenity-rs/songbird#255]
**Songbird version:** 0.4.3

**Rust version (`rustc -V`):** 1.81.0

**Twilight version:** 0.15.4

**Description:**
In version 0.4.3 (PlayMode::End == PlayMode::Stop) returns true, whereas in version 0.3.2 it returns false.
Is there a new way to determinate whether a track has ended naturally or was stopped manually?

**Steps to reproduce:**
`assert_eq!(PlayMode::End, PlayMode::Stop);`

**Comment by FelixMcFelix** [comment]
Thanks for the report; I believe I did this to support some particular event behaviour around having track errors and stop *both* fire a track end handler. I'm not convinced that delegating to the inner track event type for equality is quite right as far as user-visible APIs are concerned.

In the meantime, the language should allow you to just match directly:

```rust
// via match
match play_mode {
    PlayMode::End => {},
    PlayMode::Stop => {},
    _ => {},
}

// or if you only care about one branch
let manually_stopped: bool = matches!(play_mode, PlayMode::Stop);
```

**Comment by penguingl** [comment]
Thanks a lot!
