### ISSUE TITLE
InterconnectError when calling manager.remove

### ISSUE THREAD

**Issue by peppizza** [serenity-rs/songbird#26]
`ERROR runner{config=Config { crypto_mode: Normal, decode_mode: Decrypt, preallocated_tracks: 1 }}: songbird::driver::tasks::mixer: Mixer thread cycle: InterconnectFailure(Event)
thread '<unnamed>' panicked at 'FATAL: No way to rebuild driver core from mixer.: "SendError(..)"', /home/spencer/.cargo/git/checkouts/songbird-bfb5fd0fe254c2b1/f222ce9/src/driver/tasks/mixer.rs:234:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace'`

I am unsure as to what is causing this error, but it seems to occur everytime i call manager.remove.  It doesn't seem to cause any problems, (that I know of), but regardless, it still exists

**Comment by FelixMcFelix** [comment]
I've been seeing it too, I think it's an overzealous (and noisy) panic. It's caused by the core task exiting before the driver -- it should be harmless, but it's annoying to see yes.

**Comment by peppizza** [comment]
Is there a way it can be re-ordered to exit the driver first, or would it be better to just suppress the error
