### ISSUE TITLE
Track start event?

### ISSUE THREAD

**Issue by peppizza** [serenity-rs/songbird#29]
Is there an event i can register to get fired on a track starting, similar to that of a track ending

**Comment by FelixMcFelix** [comment]
Not at present, no. Play/Pause (i.e., changes to `PlayMode`) would be useful additions to `TrackEvent`.

For now, I think you can work around this by adding a timed event to a track which fires in the first 20ms (i.e., set it to 5ms or similar). These fire based on the playback time for a track, so a track which transitions from paused to playing will fire this event in the same "tick" as the track starts (assuming this relates to queued tracks).

**Comment by peppizza** [comment]
I assume you mean using the delayed event?

**Comment by saanuregh** [comment]
@peppizza depending upon ur requirement this might not be useful, but to display an embed on track start, I implemented a track end event like this:
https://github.com/saanuregh/bowot-rs/blob/553ce71047c8f8a0c9c8f5ebfb1abaa4de095d03/src/commands/music.rs#L35
But, this method will not display the embed for the first track enqueued.

**Comment by peppizza** [comment]
@saanuregh I achieved something very similar to that except checking for the empty queue when the event is created, and not creating it if its the first song
