### ISSUE TITLE
Plans to publish a crate?

### ISSUE THREAD

**Issue by dseevr** [serenity-rs/songbird#5]
Will there be a songbird crate on crates.io eventually?  Should probably reserve the name now since it seems to be available

**Comment by FelixMcFelix** [comment]
Full crate release is dependent on [serenity's](https://github.com/serenity-rs/serenity/) version 0.10.0 being published. As much as I despise crate squatters, it wouldn't hurt for us to publish a `v0.0.1-pre` which redirects users to the repo in the interim.

**Comment by FelixMcFelix** [comment]
We've reserved the [songbird name](https://crates.io/crates/songbird) and have active links to this repository and our documentation. Thanks!
