### ISSUE TITLE
Songbird::join to already joined channel deadlocks

### ISSUE THREAD

**Issue by DoumanAsh** [serenity-rs/songbird#59]
Subj.
If you attempt to join on the same channel as you previously joined, join call gets stuck

**Comment by FelixMcFelix** [comment]
This should be handled in the next breaking version by #47. This isn't technically a deadlock, for the reasons explained there, but can't be put on crates.io until then due to breaking changes in other functions.

**Comment by DoumanAsh** [comment]
Ok, for now if I would be able to know channel id I can avoid joining the same channel instead of exiting current channel each time music ends)
