### ISSUE TITLE
Calling SongBird::join() while already in the voice channel causes a deadlock

### ISSUE THREAD

**Issue by jtscuba** [serenity-rs/songbird#66]
**Songbird version:** 0.1.6

**Rust version (`rustc -V`):** 1.51

**Serenity/Twilight version:** 10.5

**Features:** (Songbird & Serenity)
``` 
[
    "driver-tokio-02",
    "gateway-tokio-02",
    "serenity-rustls-tokio-02",
]

```

**Description:**
Calling SongBird::join() while already in the voice channel causes a deadlock. The second call to join will never return. 
**Steps to reproduce:**

Modify the serenity voice example to call join twice in the `join` command. The second one should return an error or be idempotent and succeed. Either way it shouldn't deadlock the bot.
```
voice_manager.join(guild_id, voice_channel_to_join).await;
voice_manager.join(guild_id, voice_channel_to_join).await;
```

**Comment by FelixMcFelix** [comment]
Thanks for the detailed bug report! This issue is fixed in the next breaking release by #47.

Until then, you will need to check join state yourself. I hope to have a pre-release up soon -- there were one or two further changes I wanted to fit in, but have been busy with work.
