### ISSUE TITLE
channel closed error when using handle.enable/disable_loop

### ISSUE THREAD

**Issue by peppizza** [serenity-rs/songbird#9]
I'm trying to make a command to enable/disable a loop on the current track playing, however I keep getting the error `SendError(TrackCommand::Loop(Infinite)), channel closed`

code:
```rust
if let Some(handler_lock) = manager.get(guild_id) {
        let handler = handler_lock.lock().await;
        let queue = handler.queue();

        if let Some(handle) = queue.current() {
            if let LoopState::Infinite = handle.get_info()?.await?.loops {
                if let Err(why) = handle.disable_loop() {
                    tracing::error!("{:?}, {}", why, why);
                }

                msg.reply(ctx, "Stopped loop").await?;
            } else {
                if let Err(why) = handle.enable_loop() {
                    tracing::error!("{:?}, {}", why, why);
                }

                msg.reply(ctx, "Enabled loop").await?;
            }
        }
    }
```

produces: `ERROR music_bot::commands::loop_command: SendError(TrackCommand::Loop(Infinite)), channel closed`

**Comment by FelixMcFelix** [comment]
A `SendError` implies that the receive side has been dropped. Either the track has ended and been removed internally by the driver, or it's failing to play in the first place. Do you hear anything before you set loop state?

**Comment by peppizza** [comment]
The track was playing when the loop command was run

**Comment by FelixMcFelix** [comment]
I think the issue here is that the `Input` you created was not seekable. I think you should use a [restartable variant](https://serenity-rs.github.io/songbird/current/songbird/input/restartable/struct.Restartable.html#method.ytdl) in this case: this is not the default as it has slightly higher overhead.

This particular failure mode for loop commands could be made clearer in docs.

**Comment by peppizza** [comment]
Is there a way to get the metadata from a Restartable::ytdl call?

**Comment by FelixMcFelix** [comment]
`Input::from(Restartable::ytdl(url))` should suffice here to pass through metadata to a usable `Input`.

**Comment by peppizza** [comment]
Thanks for the help!
