### ISSUE TITLE
Why not generics?

### ISSUE THREAD

**Issue by nanai10a** [serenity-rs/songbird#94]
Why [Songbird::get](https://docs.rs/songbird/0.2.0/songbird/struct.Songbird.html#method.get) have generics (`<G: Into<GuildId>>`), but [Songbird::get_or_insert](https://docs.rs/songbird/0.2.0/songbird/struct.Songbird.html#method.get_or_insert) doesn't have generics?
And, why [Call](https://docs.rs/songbird/0.2.0/songbird/struct.Call.html) methods doesn't have generics?

**Comment by FelixMcFelix** [comment]
This is an oversight, sorry! If you want to remedy this, I'd be happy to take a PR on `songbird:next`.

**Comment by nanai10a** [comment]
I'm thinking of `mongodb` as a sample to this issue, but there's something I'm curious about:

```rs
fn example(param: impl Into<Param>) { /* --- snip --- */ }
```

```rs
fn example<T: Into<Param>>(param: T) { /* --- snip --- */ }
```

Which should this be? As an example, `ytdl` and `mongodb` (approximately) is the former, but `ffmpeg` and #102 are the latter ...
