### ISSUE TITLE
Missed and delayed events when adding multiple track events

### ISSUE THREAD

**Issue by evanc577** [serenity-rs/songbird#95]
**Songbird version:** 0.2.0

**Rust version:** rustc 1.55.0 (c8dfcfe04 2021-09-06)

**Serenity version:** 0.10.9

**Description:**

Setting multiple events on one track causes some strange behavior and missed events.

I am trying to add events that will skip certain parts of a track by adding a timed event, which when triggered will seek forward and then add another timed event to skip the next part. But I am running this issue where events are not being triggered. Is there a better way to do this?

**Steps to reproduce**:

Create an event that logs whenever it is triggered.

```rust
#[derive(Debug)]
struct EventTester {
    message: String,
}

#[async_trait]
impl VoiceEventHandler for EventTester {
    async fn act(&self, _ctx: &EventContext<'_>) -> Option<Event> {
        event!(Level::INFO, "EventHandler: {}", self.message);
        None
    }
}
```

Play a song and add some events.

```rust
let song = handler.play_source(source);

song.add_event(
    Event::Delayed(Duration::from_secs(1)),
    EventTester {
        message: "delayed 1".into(),
    },
)
.unwrap();
song.add_event(
    Event::Delayed(Duration::from_secs(2)),
    EventTester {
        message: "delayed 2".into(),
    },
)
.unwrap();
song.add_event(
    Event::Periodic(Duration::from_secs(1), Some(Duration::from_secs(0))),
    EventTester {
        message: "periodic 1".into(),
    },
)
.unwrap();
song.add_event(
    Event::Periodic(Duration::from_secs(2), Some(Duration::from_secs(0))),
    EventTester {
        message: "periodic 2".into(),
    },
)
.unwrap();
```

The 1 second delay event is only run after the 2 second delay event, and the 1 second periodic event is lost completely.

```
[2021-09-27T18:10:29Z INFO  discord_bot] EventHandler: delayed 2 
[2021-09-27T18:10:29Z INFO  discord_bot] EventHandler: delayed 1 
[2021-09-27T18:10:29Z INFO  discord_bot] EventHandler: periodic 2 
[2021-09-27T18:10:31Z INFO  discord_bot] EventHandler: periodic 2 
[2021-09-27T18:10:33Z INFO  discord_bot] EventHandler: periodic 2 
[2021-09-27T18:10:35Z INFO  discord_bot] EventHandler: periodic 2 
[2021-09-27T18:10:37Z INFO  discord_bot] EventHandler: periodic 2 
[2021-09-27T18:10:39Z INFO  discord_bot] EventHandler: periodic 2
```

**Comment by FelixMcFelix** [comment]
I'll try and look into this later tonight -- this may be related to #92? I've been quite busy with a new job lately, so my time's a little constrained these days.

**Comment by FelixMcFelix** [comment]
I realise now why this is happening! All events were being added, but only one was being cleared: the `BinaryHeap` of timed events is supposed to be a min-heap, but `EventData`'s `Ord` wasn't reversed to account for this. Will have a fix up shortly.

**Comment by evanc577** [comment]
Thanks for the quick fix!
