### ISSUE TITLE
Calling `songbird::remove` from Periodic Event Handler/Separate Thread Hangs

### ISSUE THREAD

**Issue by dfontana** [serenity-rs/songbird#98]
`Songbird` version: `0.2.0`
`Serenity` version: `0.10.9`
`Rust` version: `1.55.0`

## Overview

- Goal: Disconnect bot from voice channel after inactivity
- Issue: When calling `remove` or `leave` from an event handler, the bot does not disconnect from voice. At the same time, it no longer responds to any other voice commands issued (eg a stop, play, etc). When running the same code from a serenity command, however, the bot disconnects as expected. 

To rule out any event handler/async_trait related issues, I tried just spawning a `tokio::task` to run the event handler's code. This too failed to disconnect the bot; which seems to narrow the problem down to something with `Songbird::remove` on an instance of `Songbird` that is `clone`'d outside of a Serenity command's scope.

Perhaps my approach to disconnecting from voice after a period of time is wrong altogether?

## Code Example

First attempt with Periodic Global Event Handler:

<details>
    <summary>Click here</summary>

```rust
handler.add_global_event(
    Event::Periodic(Duration::from_secs(30), None),
    ChannelDisconnect {manager, guild: guild_id},
);

// Channel Disconnect impl
struct ChannelDisconnect {
  manager: Arc<Songbird>,
  guild: GuildId,
}

#[async_trait]
impl EventHandler for ChannelDisconnect {
  async fn act(&self, _ctx: &EventContext<'_>) -> Option<Event> {
     match self.manager.get(self.guild) {
      None => None,
      Some(handler_lock) => {
        let handler = handler_lock.lock().await;
        if handler.queue().is_empty() {
          let _dc = self.manager.remove(self.guild).await;
        }
        None
      }
    }
  }
}
```

</details>

Second attempt with tokio

<details>
    <summary>Click here</summary>

```rust
let chan = ChannelDisconnect {manager: manager.clone(), guild: guild_id.clone()};
task::spawn(async move {
  let interval = time::interval(Duration::from_secs(30));
  interval.tick().await;
  loop {
     interval.tick().await;
     match chan.manager.get(chan.guild) {
      None => None,
      Some(handler_lock) => {
        let handler = handler_lock.lock().await;
        if handler.queue().is_empty() {
          let _dc = chan.manager.remove(chan.guild).await;
        }
        None
      }
    }
  }
});
```

</details>

**Comment by FelixMcFelix** [comment]
The problem here is that you're causing a deadlock:
* `get` returns a lock, which you lock.
* `remove` calls `Songbird::leave` internally, which also calls `get`->`lock`->`Call::leave`
Perhaps try:
```rust
let _dc = handler.leave().await;
```
I think this still captures the logic you're going for. If you want to completely destroy the call, then you can do something like:
```rust
let drop_call = match chan.manager.get(chan.guild) { /* return bool in here: true if handler.leave().await was called */ };
if drop_call { chan.manager.remove(chan.guild).await; }
```

**Comment by dfontana** [comment]
Ah shucks, that was it 🤦 Thanks @FelixMcFelix, apologies for the Issue!
